# Generated by Django 3.0.3 on 2020-03-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post10_post2_post3_post4_post5_post6_post7_post8_post9'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.DateField()),
            ],
        ),
    ]
