# Generated by Django 3.0.3 on 2020-03-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post15'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Floatnumber', models.FloatField()),
            ],
        ),
    ]
