# Generated by Django 3.0.3 on 2020-03-09 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200304_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Mark_Obtained',
            new_name='english',
        ),
        migrations.AddField(
            model_name='student',
            name='maths',
            field=models.IntegerField(),
            
        ),
        migrations.AddField(
            model_name='student',
            name='science',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='social',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
