# Generated by Django 3.0.3 on 2020-03-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200309_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='std',
            new_name='Branch',
        ),
    ]
