# Generated by Django 3.0.3 on 2020-03-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200310_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_id', models.IntegerField()),
                ('car_amount', models.IntegerField()),
                ('car_details', models.CharField(max_length=100)),
                ('car_model', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Emp_id', models.IntegerField()),
                ('Emp_salary', models.IntegerField()),
                ('Emp_email', models.EmailField(max_length=254)),
                ('Emp_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('product_amount', models.IntegerField()),
                ('product_details', models.CharField(max_length=100)),
            ],
        ),
    ]
