# Generated by Django 3.0.4 on 2020-03-20 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects_name',
            name='science',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Details.Science_mark'),
        ),
        migrations.AlterField(
            model_name='subjects_name',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Details.Social_mark'),
        ),
    ]
